/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sunny_helloffmpeg_NativeFFplayer */

#ifndef _Included_com_sunny_helloffmpeg_NativeFFplayer
#define _Included_com_sunny_helloffmpeg_NativeFFplayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sunny_helloffmpeg_NativeFFplayer
 * Method:    native_avcodecInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sunny_helloffmpeg_NativeFFplayer_native_1avcodecInfo
  (JNIEnv *, jclass);

/*
 * Class:     com_sunny_helloffmpeg_NativeFFplayer
 * Method:    native_stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sunny_helloffmpeg_NativeFFplayer_native_1stringFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_sunny_helloffmpeg_NativeFFplayer
 * Method:    native_avcodecConfiguration
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sunny_helloffmpeg_NativeFFplayer_native_1avcodecConfiguration
  (JNIEnv *, jclass);

/*
 * Class:     com_sunny_helloffmpeg_NativeFFplayer
 * Method:    native_playVideo
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_sunny_helloffmpeg_NativeFFplayer_native_1playVideo
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_sunny_helloffmpeg_NativeFFplayer
 * Method:    play
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sunny_helloffmpeg_NativeFFplayer_play
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sunny_helloffmpeg_NativeFFplayer
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sunny_helloffmpeg_NativeFFplayer_stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
